source 'https://rubygems.org'
ruby '2.6.6'

gem 'rails', '~> 5.2.0'

gem 'mongo'
gem 'bson'
gem 'mongoid', '~> 6.0'

gem 'json'
gem 'memcachier'
gem 'dalli'
gem 'omniauth', '~> 1.0'
gem 'omniauth-twitter'
gem 'tweet-button'
gem 'newrelic_rpm'
gem 'unicorn'
gem 'rack-timeout'
gem 'sprockets-rails', '~> 2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.0.3'
gem 'kaminari'

gem 'vimgolf', path: 'lib/vimgolf'

group :test, :development do
  gem 'rspec-rails', '3.6.0'
  gem 'rails-controller-testing'
  gem 'shoulda-matchers'
  gem 'simplecov', :require => false
  gem 'codeclimate-test-reporter', '~> 1.0.0'
  gem 'capybara'
  gem 'execjs'
  gem 'mini_racer'
  gem 'launchy'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'poltergeist'
  gem 'phantomjs', :require => 'phantomjs/poltergeist'
  gem 'factory_bot', '~> 4.0'
  gem 'faker'
  gem 'rubocop', '~> 1.9.1'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
end
